### ISSUE TITLE
`Cannot` find module '../saucelabs.creds.json'

### ISSUE THREAD

**Issue by fabriciolemos** [FountainJS/fountain#45]
I want to make some experiments with the generators, so I cloned this repo but, even before any modifications, I am getting this error when running `npm test`:

```
$ npm test

fountain@1.0.0 test /Users/fabricio/development/projects/fountain-js/fountain
mocha test/travis

module.js:442
  throw err;
  ^

Error: `Cannot` find module '../saucelabs.creds.json'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/fabricio/development/projects/fountain-js/fountain/test/helpers/wdio-helper.js:24:26)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/fabricio/development/projects/fountain-js/fountain/test/travis.js:8:14)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at /Users/fabricio/development/projects/fountain-js/fountain/node_modules/mocha/lib/mocha.js:220:27
  at Array.forEach (native)
  at Mocha.loadFiles (/Users/fabricio/development/projects/fountain-js/fountain/node_modules/mocha/lib/mocha.js:217:14)
  at Mocha.run (/Users/fabricio/development/projects/fountain-js/fountain/node_modules/mocha/lib/mocha.js:469:10)
  at Object.<anonymous> (/Users/fabricio/development/projects/fountain-js/fountain/node_modules/mocha/bin/_mocha:404:18)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.runMain (module.js:575:10)
  at run (node.js:348:7)
  at startup (node.js:140:9)
  at node.js:463:3
npm ERR! Test failed. See above for more details.
```
#### Configuration

Root fountain repository, with no modifications
#### Version

a98e4f4de136d84d25ee4f0c15d8b04035dc5d74
#### Node/NPM/OS versions

Node 6.2.2
NPM 3.10.3
OS X 10.11.5

**Comment by micaelmbagira** [comment]
Hi @fabriciolemos `npm test` in this repo runs our integration tests through Saucelabs so you cannot run them. Actually, this repo doesn't have any unit test, but the submodules do.
